### PR TITLE
Revamped

### PR DESCRIPTION
**Pull request by davidgatti**
# Issue #

Misleading and unclear documentation

# Description of changes

Complete change to give readers a better understanding on how to make a virtual machine using Amazon Linux 2. This change was triggered after this from thread https://forums.aws.amazon.com/thread.jspa?messageID=828964&tstart=0, where I realized that the article was not changed despite the promise that someone would. My hope is this is a more clear and straight forward explanation.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by meiringa** [comment]
Hello, 

Thank you for providing this feedback. I will review your changes and then update the guide as required.
Thank you for helping us to improve our documentation.

**Comment by davidgatti** [comment]
No worries, and please take a looks at my gramma, English is not my primary language :)

**Comment by meiringa** [comment]
Hi davidgatti, I'm going to make the changes directly in the guide and close the pull request. This will get updated in our next refresh. Thanks!

**Comment by davidgatti** [comment]
If you are doing it directly then what is the point of me taking the time to write everything so it formats well and then open a PR, if you are going to discard it? :)

**Comment by nrdlngr** [comment]
Sorry @davidgatti, I think this was an oversight. I spoke to @meiringa shortly after this was closed and we agreed to reopen the PR and work with you to get your contribution included through this process, but it looks like that slipped through the cracks.

I tried reopening this PR, but it looks like you deleted your branch. If you want to resubmit, we'll make sure to work with you to get your contribution merged properly.

Thanks for understanding.

**Comment by davidgatti** [comment]
Hmmm.. done.

**Comment by meiringa** [comment]
My apologies, @davidgatti. I have reopened your pull request. As @nrdlngr mentioned, we'd like to work with you to make sure that we get your contribution merged.

**Comment by davidgatti** [comment]
@meiringa, sure, the patch is there, use it, don't use it, what do I care. Your not know for the best docs on the net, and I'm starting to understand why - I hoped I can help out and improve things that you don't care to improve, but now it seams clear where the problem is. 

This will be my last post, since I don't have time to teach you how GitHub and contributions works.

To sum it up, the patch was re-added, you can use it, you can delete it, you can discard it. It is your doc, not mine.

**Pull request merged**
