### PR TITLE
linked accounts with dedicated instances - limitation

### PR DESCRIPTION
**Pull request by drenner1992**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by meiringa** [comment]
Hello, 
Thank you for you contribution! I'll review your changes and update the docs as you have suggested.
Thanks again!

**Comment by drenner1992** [comment]
Thanks

I’m responsible for technical documentation in my current role and I’ve come across a few other changes I’d like to make (although I have to admit your documentation is already pretty impressive).

One page I want to edit is the Elastic Network Interfaces page, however, I cannot find it in this repo :(

Sent from my iPhone

On 29 Mar 2018, at 2:07 pm, meiringa <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
Thank you for you contribution! I'll review your changes and update the docs as you have suggested.
Thanks again!

**Comment by julieso** [comment]
The Elastic Network Interfaces page is using-eni.md.

**Comment by meiringa** [comment]
Hello,
I have updated our docs as you have suggested. You should see your changes with our next refresh. Thanks!

**Comment by drenner1992** [comment]
Thanks, FYI, on the homepage where the customer stories are listed ... all of the logos have a transparent background except for lyft (start ups) which has a white background.

Sent from my iPhone

On 6 Apr 2018, at 6:53 am, meiringa <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
I have updated our docs as you have suggested. You should see your changes with our next refresh. Thanks!

**Comment by meiringa** [comment]
Good catch!! I will point this out to the marketing team. Thank you.

**Comment by drenner1992** [comment]
Hi team

I don't have the time to fork your repo and fix it, however, there's a typo on this page: https://aws.amazon.com/premiumsupport/knowledge-center/ebs-volume-charges/



You are billed for the total amount of storage provisioned to your account, no matter if of whether the storage is used or not. For example, if you provision a 100-GB EBS volume for a month, but only store 1 GB of data on that volume, you are still billed for 100 GB/m of EBS storage.


I'm guessing it should be...

You are billed for the total amount of storage provisioned to your account, regardless of whether the storage is used or not. For example, if you provision a 100-GB EBS volume for a month, but only store 1 GB of data on that volume, you are still billed for 100 GB/m of EBS storage.

________________________________

**Pull request closed without merging**
