### PR TITLE
Add resolution tip to Unsafe AuthorizedKeysCommand "/opt/aws/bin/eic_run_authorized_keys": bad ownership or modes for directory /

### PR DESCRIPTION
**Pull request by coreykck**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by lindseyspirit** [comment]
Thank you for your pull request. I am looking into the error and will update you on status.

**Comment by lindseyspirit** [comment]
@coreykck is it possible to let us know the AMI and sshd config you were using when you received this error?

**Comment by LordAlfredo** [comment]
The proposed fix looks like it's adding execute permission back onto the root directory.  I'm confused why that was removed in the first place - removing the execute permission bit on a directory means that the affected users cannot access any files in that directory.  In this case in particular, removing it from root (ie, giving root 754 or 554 permissions) means that _only the root user_ may list and access files in the root directory.  This can break certain system components - you probably had other processes silently failing.

The ssh daemon is particularly sensitive in that it checks if the root directory (and standard subdirectories such as /usr, /lib, etc) have "normal" Linux filesystem permissions - namely, they should be owned by the root user/group and have 755 or 555 permissions.  Changing either ownership or permissions on directories that sshd checks will cause this error.

Are you running a specific AMI or EC2 user data script that changes root's permissions?  The standard Amazon Linux 2 AMI has root owned by "root:root" with permissions set to 555.

**Comment by coreykck** [comment]
Hi all,
The Ami I'm using is an AWS LINUX AMI2
No specific work done on that
Apache + PHP.
Shhd was from the ami, no tweaks. Ec2-instance-connector was installed from
yum (as reported in doc); sshd configuration was done by yum during package
installation.
I hope thi helps
Bye
Corrado

Il lun 16 dic 2019, 18:46 Daniel Anderson <notifications@github.com> ha
scritto:

**Comment by kppahare** [comment]
Hi @coreykck - Did you get a chance to test the issue with a new instance with the same image? Does the issue persist? 
If yes, could you please attach the output of ls -hal / .

**Comment by lindseyspirit** [comment]
Hi @coreykck. Just checking whether you had  a chance to test the issue with a new instance with the same image. See previous message.

**Comment by lindseyspirit** [comment]
no response

**Pull request closed without merging**
