### PR TITLE
Correct AWS GovCloud public certificate

### PR DESCRIPTION
**Pull request by jaken551**
The AWS public certificate for AWS GovCloud Region (US-Gov-West) was updated to an incorrect certificate. I spent a good bit of time chasing an issue down due to this. I would love to see the docs updated so others won't have the same problem.

*Description of changes:*

- Correct AWS public cert
- Change grammar and use proper GovCloud region name

### CODE REVIEW

**Comment by mariflax** [comment]
Hi @jaken551. Thank you for telling us about this issue. We intentionally changed the certificate a little while ago to the pkcs7 certificate. However, given what you've said above, a member of the team will be looking into this, and I'll provide an update here.

**Comment by meiringa** [comment]
Hi, I'm looking into this issue. I will provide feedback shortly.

**Comment by meiringa** [comment]
Hi @jaken551 , 

I'd like to get some more information so that we can investigate further, but your profile doesn't provide any contact information. 

If it's not too much trouble, please can you submit documentation feedback using the EC2 docs feedback form [https://docs-feedback.aws.amazon.com/feedback.jsp?hidden_service_name=EC2&topic_url=http://docs.aws.amazon.com/en_us/AWSEC2/latest/UserGuide/concepts.html] and provide the following information:

1. instance ID
2. availability zone
3. your email address

You can mention my name in the feedback and I'll pick it up.

Thanks
Ashley

**Comment by meiringa** [comment]
Hello, I'm closing the Pull Request for now. The certificate that we currently have in the docs is the correct one. But please do not hesitate to contact us if you're still experiencing issues. Thank you.

**Pull request closed without merging**
