### PR TITLE
Clarification on Spot EC2 Partial Hour Billing

### PR DESCRIPTION
**Pull request by jsbonso**
*Issue #, if available:* Clarification needed on Spot EC2 Partial Hour Billing 

*Description of changes:*

Hi Team,

I would like to request for clarification regarding the Spot Instance pricing. Say I have a Spot request with a maximum price of $0.04 which has been successfully fulfilled and the instance has already been running for 90 minutes (past the first instance hour). The Spot Price goes up to $0.05 which will automatically result in the interruption/termination of my instance. 

Will I be billed with $0.06 for that 90 minutes ($0.04 + $0.02), or will I only be paying $0.04, not counting the last 30 minutes?

Based on this document, including the official EC2 FAQ, the answer should be $0.06 since the instance was interrupted in the subsequent hour. In the "Specifying a Duration for Your Spot Instances" section, there is a paragraph that says: 

> "You are billed at this price for each hour or partial hour that the instance is running. A partial instance hour is billed to the nearest second."

The official EC2 FAQ also says that: 

Q. How will I be charged if my Spot instance is interrupted?

> If your Spot instance is terminated or stopped by Amazon EC2 in the first instance hour, you will not be charged for that usage. However, if you terminate the instance yourself, you will be charged to the nearest second. If the Spot instance is terminated or stopped by Amazon EC2 in any subsequent hour, you will be charged for your usage to the nearest second. If you are running on Windows and you terminate the instance yourself, you will be charged for an entire hour.

Reference: [https://aws.amazon.com/ec2/faqs/](https://aws.amazon.com/ec2/faqs/)

However, there seems to be a conflicting document that says otherwise. In the "How Spot Instances Work" document, it says:

> "If you terminate your instance, you pay for any partial hour used (as you do for On-Demand or Reserved Instances). However, you are not charged for any partial hour of usage if the Spot price goes above your maximum price and Amazon EC2 interrupts your Spot Instance."

Reference: [https://docs.aws.amazon.com/whitepapers/latest/cost-optimization-leveraging-ec2-spot-instances/how-spot-instances-work.html](https://docs.aws.amazon.com/whitepapers/latest/cost-optimization-leveraging-ec2-spot-instances/how-spot-instances-work.html)

This is where the confusion is. It says that you are not charged for any partial hour of usage, which contradicts the first two documents above. Hence, I would like to ask for clarification regarding this specific statement from the above paragraph:

> "However, you are not charged for any partial hour of usage if the Spot price goes above your maximum price and Amazon EC2 interrupts your Spot Instance."

In relation to the example that I mentioned above, does the phrase: "partial hour of usage" only refers to the first instance hour, and not the subsequent hour? This document is quite ambiguous and personally, it seems that this should be updated to avoid any confusion to the readers. 

Thank you in advance for your assistance. Looking forward to your reply.

Cheers,
Jon Bonso

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jsbonso** [comment]
Hi Team, @julieso,

Good day, wondering if you have time to check this out? Would be great if you can shed some light on these 2 contradicting AWS documents. 

Thanks in advance!

Cheers,
Jon Bonso

**Comment by mariflax** [comment]
Hi Jon,

I do apologise for the delay in getting back to you.

Thanks for letting us know that the information is confusing. I've tried to make it as clear as possible below, although I am seeking clarification to make sure I am 100% correct. I will let you know as soon as I get confirmation, and I will also update the doc with this information.

For regular Spot Instances (not Spot Blocks), you’re charged as follows:

If *you* interrupt the Spot Instances:

- In the first hour:
-- Charged for seconds used (Amazon Linux and Ubuntu)
-- Charged for the hour (Windows, SUSE, RHEL)

- In any hour after the first hour:
-- Charged for the seconds used (Amazon Linux and Ubuntu)
-- Charged for the hour even if you used a partial hour (Windows, SUSE, RHEL)

If *Amazon EC2* interrupts the Spot Instance:

- In the first hour:
-- No charge

- In any hour after the first hour:
-- Charged for the seconds used (Amazon Linux and Ubuntu)
-- Charged for the hour even if you used a partial hour (Windows, SUSE, RHEL)

For Spot Block (not regular Spot Instances):
- If you interrupt the Spot Instance in any hour of the Spot Block, you are charged for the full Spot Block
- If Amazon EC2 interrupts the Spot Instance before the Spot Block has completed, you are charged nothing

Kind regards,
Marilyn Flax
AWS Documentation

**Comment by jsbonso** [comment]
Thank you so much @mariflax! I'll wait for your confirmation then.

**Comment by varunbabu008** [comment]
Is there any official confirmation on this ?

**Comment by mariflax** [comment]
Hi again,

I have official confirmation on this content, as follows:

The only difference to what I'd posted originally is in the last bullet (see below)--if Amazon EC2 interrupts the Spot Instance in any hour after the first hour, for Windows, SUSE, and RHEL you're charged up to the last full hour, *but you're not charged for the current partial hour*. The rest of the content, as I'd posted before, is unchanged.

If you interrupt the Spot Instances:

    In the first hour:
    -- Charged for seconds used (Amazon Linux and Ubuntu)
    -- Charged for the hour even if you used a partial hour (Windows, SUSE, RHEL)

    In any hour after the first hour:
    -- Charged for the seconds used (Amazon Linux and Ubuntu)
    -- Charged for the hour even if you used a partial hour (Windows, SUSE, RHEL)

If Amazon EC2 interrupts the Spot Instance:

    In the first hour:
    -- No charge

    In any hour after the first hour:
    -- Charged for the seconds used (Amazon Linux and Ubuntu)
    -- Charged up to the last full hour, no charge for the current partial hour (Windows, SUSE, RHEL)

Kind regards,
Marilyn Flax
AWS Documentation

**Comment by mariflax** [comment]
Please also note that if you interrupt a Spot Instance in a _Spot block_, you only pay for the seconds used (Linux) or hours used (WIndows, RHEL, SUSE). This is different to what I originally wrote above.

@jsbonso thank you for bringing this to our attention. I've added this information to the EC2 User Guide here: https://docs.aws.amazon.com/en_us/AWSEC2/latest/UserGuide/spot-interruptions.html#billing-for-interrupted-spot-instances. I'll close this request now.

**Comment by jsbonso** [comment]
Thank you so much @mariflax! Much appreciated!

**Pull request closed without merging**
