### PR TITLE
Added missing step

### PR DESCRIPTION
**Pull request by davidgatti**
It is crucial in this tutorial to restart sshd.

*Issue #, if available:*

The tutorial dose no produced the described outcome

*Description of changes:*

Added the missing step to make it work

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by meiringa** [comment]
Hi David, 

I'm looking into this pull request. I followed the steps in the guide and I was able to complete the procedure without restarting the SSH server as you suggested. I tried with a few different AMIs (AL, AL2, RHEL7, and Ubuntu), and they all worked for me. I was able to create the new user and then log in immediately without restarting SSH.

Please can you provide some more information around this? Which AMI are you using? Which step fails for you? Which error are you getting?

Thanks
Ashley

**Comment by meiringa** [comment]
Hi David, do you have any feedback on my follow-up queries?

**Comment by meiringa** [comment]
HI David, I'm closing this pull request for now. Please do re-open it if you feel that the change is still valid. Thanks again!

**Comment by davidgatti** [comment]
Sorry to many notifications. Well what can I say, under Debian 9 I had this issue and what Googling for a solution I wasn't the only one having the same problem, thus deciding to just that one extra step. If you believe that it is not needed, then there is always Google ;)

**Pull request closed without merging**
