### PR TITLE
Clarified the Pronunciation of AMI

### PR DESCRIPTION
**Pull request by rhboyd**
*Issue #, if available:*

*Description of changes:*
Clarified the Pronunciation of AMI

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by QuinnyPig** [comment]
This can be merged.

**Comment by jeffbarr** [comment]
Further research is warranted.

**Comment by michaelmoussa** [comment]
> Further research is warranted.

https://twitter.com/Werner/status/1182530158026055681

**Comment by andytechdad** [comment]
+2

**Comment by nie7321** [comment]
I believe the official pronunciation is ['a-'mi]?

**Comment by lindseyspirit** [comment]
Thank you all for the extremely valuable technical input on this topic. Terminology pronunciations are currently not in scope for the EC2 User Guide.

**Pull request closed without merging**
